### ISSUE TITLE
Add support for create_operator

### ISSUE THREAD

**Issue by veganstraightedge** [teoljungberg/fx#114]
Hi. Thanks for making `fx`! it helped me clean up the company's big rails app's migrations quite a bit.

# Currently

Sadly, we still have to use `db/structure.sql`.
I'd prefer if we could go back to using `db/schema.rb`.

The one last thing that stands between here and there is a custom operator.

Currently, we have this code in the same migration with all of our `create_function ...` calls:

```ruby
# TODO: figure out if/how we can express this so it ends up in schema.rb:
execute <<~SQL.squish
  CREATE OPERATOR ||+ (LEFTARG = TEXT,  RIGHTARG = TEXT, PROCEDURE = immutable_concat);
SQL
```

I'd rather have:

```ruby
create_operator :pipe_pipe_plus
```

***

This line of code:

```SQL
CREATE OPERATOR ||+ (LEFTARG = TEXT,  RIGHTARG = TEXT, PROCEDURE = immutable_concat);
```

is depended on by a few lines of code in migrations like this:

```ruby
t.index "(((((name)::text ||+ (location_line_1)::text) ||+ (location_city)::text) ||+ (location_region)::text)) gin_trgm_ops", name: "index_jobs_1_gin", using: :gin
```

I tried, just in case, doing a `create_operator :pipe_pipe_plus` along with all of our `create_function`s.  
This raises a `NoMethodError` for #create_operator, obviously.

I tried being sneaky and doing `create_function :pipe_pipe_plus`.
This didn't blow up, but then didn't end up in `db/schema.rb`.

I'm assuming that this is because `db/schema.rb` has no concept of `create_operator` like it has `create_function`, `create_trigger`, `create_view`, et al (?).

# Feature request 

Could you add a `create_operator` method that works just like `create_function`, which looks for a file named the same as the passed in symbol arg but in a `db/operators` folder instead of `db/functions`?

And then :hand wave: (I don't know what this would take), also get that to work in `db/schema.rb` please?

That would make me so happy.

**Comment by teoljungberg** [comment]
I've never had to create custom operators, nor ever thought that I could.

I'm unsure if makes sense for F(x), but PostgreSQL mentions operators in the same breath as functions - so I guess it hold some merit to it.

I won't have the bandwidth to dig into this myself - but I'd entertain discussing this in a PR if someone opens it. I'm still not sure if this makes sense into F(x) proper or if it should be a gem on its own named `fx-operator` or similar.

**Comment by veganstraightedge** [comment]
Thanks @teoljungberg. Sadly, I don't have the know how to add this behavior to `fx`. So I probably won't be the one to PR it. But maybe someone else will come along and see this and take it up.

**Comment by veganstraightedge** [comment]
@Spaceghost, thanks for taking an initial shot at this! Have you been able to make any more progress on this issue?

@fatkodima following up with you too. Any luck getting started on this?

@GUI Any interest in digging into adding support for custom operators?

Maybe yall can combine efforts and collaborate on a complete solution tougher?

**Comment by teoljungberg** [comment]
I'm still not sure I want to include this into fx proper. To test out the waters, I'd suggest creating a separate gem that adds this as an extension to fx, and if that gains mainstream and popularity enough - I'll happily include it.

**Comment by fatkodima** [comment]
@veganstraightedge Did not started, waited to see if existing efforts would be finished. If other people wouldn't finish it (or do not want to), I can try to do it, just ping me.

**Comment by veganstraightedge** [comment]
Hi @teoljungberg. For our specific needs, we've worked around this in a different way. (By eliminating our codebase's use of the custom PG operator `||+`). I/we don't have need for this anymore. 

I'm closing out this issue.
I appreciate your openness to the possibility though. 🎉

**Comment by Spaceghost** [comment]
@veganstraightedge I have the simple operator interface working as described in https://www.postgresql.org/docs/current/xoper.html  but to make it complete I’ve got to add and document the rest from https://www.postgresql.org/docs/current/xindex.html to make it more usable for performance. It comes with caveats I’ll have to address like operator classes and families if you want your custom types available as data types for columns for your operators to work with.

@teoljungberg I think it’s fair not to include the considerably more advanced user-defined operators in the fx gem, but seeing as the operator’s functions are managed by and use the fx library for managing functions, mirrors the test layout, and follows how fx does things it would fit in fairly nicely. If you feel strongly against including it, I’d personally rather contribute to fx than decide whether I’d like to be a maintainer of a downstream project that uses fx’s library code.
