### ISSUE TITLE
Unable to generate fx:trigger

### ISSUE THREAD

**Issue by jasonjho** [teoljungberg/fx#14]
When trying to run a simple `generate` command based on the README

```rails generate fx:trigger uppercase_user_name```

I am seeing the following output: 

```No value provided for required arguments 'table_name'```

It's not clear based on the documentation what `table_name` is. 

Any ideas?

**Comment by splybon** [comment]
Was having the same issue. The readme needs to be updated so I made a PR for it.
https://github.com/teoljungberg/fx/pull/15

**Comment by teoljungberg** [comment]
Closed by #15
