### ISSUE TITLE
Code formatting options for inserting triggers/functions into schema.rb when running migrations

### ISSUE THREAD

**Issue by gregblass** [teoljungberg/fx#141]
Hey there!

I was wondering if this gem has any options as far as code formatting (tabs/spaces, number of spaces/tabs) as far as when code is inserted into schema.rb. I took the time to format the SQL how I preferred it to be - but whenever we run a migration, it is overwritten with the default/original formatting.

Feel free to just tell me "no", and I will happily live with it how it is.

Thank you!

**Comment by teoljungberg** [comment]
If we introduce formatting I'd want to have formatting be configurable to the extend that users opt into it, or out of it. As well as supporting formatters per adapter.

With that said, I don't really review nor care how the functions and triggers are formatted when they are retrieved from PostgreSQL and dumped into the schema. But rather am OK that they are presented how PostgreSQL interprets them.

Personally - I use pg_format(1) to format my SQL in its raw form, and that is what I use when I write the functions and triggers for their migrations.
