### ISSUE TITLE
Inconsistent function order on schema dumps

### ISSUE THREAD

**Issue by albaer** [teoljungberg/fx#142]
Hi! Thanks for all your work on this gem. We ran into an issue where the schema dumper would occasionally dump the functions in a different order, resulting in a diff that didn't really reflect any changes. Our workaround is something like this:

```ruby
# This monkey patches the F(x) gem so that the functions are always dumped in
# alphabetical order by name, preventing schema diffs when nothing has actually changed.
# Original code: https://github.com/teoljungberg/fx/blob/master/lib/fx/schema_dumper/function.rb
module Fx
  module SchemaDumper
    module Function
      def functions(stream)
        dumpable_functions_in_database.sort_by(&:name).each do |function|
          stream.puts(function.to_schema)
        end
      end
    end
  end
end
```
It could also be done in the `dumpable_functions_in_database` method though. If other people have this issue or if you think it would be helpful, I'd be happy to open a PR along these lines.

**Comment by teoljungberg** [comment]
Yeah ordering has been an unsolved problem for a really long time, and I haven't decided how I want to have it work. Ideally I'd want something topological to allow tables to have default values work in a decent way - and I don't want to maintain different sorting options.

Which is why I suggested to do a patch as the one you have above, as I deem this to be public API and probably won't change it.

**Comment by teoljungberg** [comment]
To be extra-safe - I'd suggest people applying a patch such as the above to subscribe for release-notifications to this project and keep track of they need to remove it once this gets some kind of upstream support.

**Comment by albaer** [comment]
Thanks for the response! That sounds good. I would also be happy to set it up as a configuration option (defaulted to false) so it wouldn't change the API, but I definitely see your point about not maintaining multiple options. If you end up wanting some help on this, I'd be happy to do some work, otherwise we'll just keep an eye on things. Thanks again for all your great work on the gem!

**Comment by bertBruynooghe** [comment]
@teoljungberg I fail to see how this change would break the API, as the result is indeterministic anyway now. I would incorporate this change always, as it at least leads to deterministic order of the functions. As the code is now, functions keep on swapping with every migration/schema dump.
(I would even go further than the above described patch and sort on name+definition, as functions can be overloaded.)
