### ISSUE TITLE
Rails 6

### ISSUE THREAD

**Issue by teoljungberg** [teoljungberg/fx#39]
With Rails 6 just being shipped, is there anything we can do get fx to work with the new version?

**Comment by perezpaya** [comment]
We have this working with no problems on production since Rails 6 rc1.

**Comment by teoljungberg** [comment]
I opened #43 for adding Rails 6.0 to the test suite.

**Comment by geoffharcourt** [comment]
@teoljungberg we've been using fx with Rails 6 since very shortly after release and haven't seen any issues. We've made several function and trigger updates.

**Comment by teoljungberg** [comment]
Beaut! Thanks @geoffharcourt
