### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by mingan** [teoljungberg/fx#61]
While the [gemspec](https://github.com/teoljungberg/fx/blob/master/fx.gemspec#L17) claims the gem is licensed under the MIT licence, the recently added [LICENSE file](https://github.com/teoljungberg/fx/blob/master/LICENSE) declares BSD-3. Which is it?

**Comment by teoljungberg** [comment]
Good point! Thanks for bringing this up, I had forgotten I had added MIT as the license in the gemspec before adding the BSD license.

I'll let MIT stand as the chosen license.
