### ISSUE TITLE
Doesn't Generate Migration File at v0.6

### ISSUE THREAD

**Issue by barash-asenov** [teoljungberg/fx#64]
When I generate a function with the generator such as in the example;

```
rails generate fx:function uppercase_users_name
```

it only generates the function but not the migration file. Reverting to 0.5 solved the issue

**Comment by barash-asenov** [comment]
It works when passing an argument as `--migration` to the generator. But isn't this supposed to be the default behavior already
when `--no-migration` is passed explicitly

**Comment by teoljungberg** [comment]
That's odd, and must be caused by #62 and #60

@bf4 - could I ask you to help submit a PR that fixes the bug?

**Comment by barash-asenov** [comment]
Yeah, that's really odd because there is a test case for that, which actually covers that it is generating a migration file. Then how this test is passing? https://github.com/bf4/fx/blob/8b5b3705e1e3904a8fa3ffca99eabe157997134e/spec/generators/fx/trigger/trigger_generator_spec.rb

**Comment by bf4** [comment]
It should just need a release.  Try bundling off master

**Comment by barash-asenov** [comment]
Yeah, seems like already fixed in the master.

**Comment by teoljungberg** [comment]
I'll cut a new release for it in that case, I must have forgotten. Sorry about that!

**Comment by teoljungberg** [comment]
Release as 5af9637
