### ISSUE TITLE
Ruby 3 support

### ISSUE THREAD

**Issue by incubus** [teoljungberg/fx#65]
Hi!

  drop_trigger does not work with Ruby 3. Unfortunately, I couldn't make a quick fix for this.
  
```$ rake db:rollback
== 20210214133450 CreateTriggerUpdateOrderSubtotal: reverting =================
-- drop_trigger(:update_order_subtotal, {:on=>:orders_items})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 2, expected 1; required keyword: on)


Caused by:
ArgumentError: wrong number of arguments (given 2, expected 1; required keyword: on)

Tasks: TOP => db:rollback
(See full trace by running task with --trace)
```

Thanks!

**Comment by teoljungberg** [comment]
Yeah that's definitely a problem, and one I would like to see fixed.

**Comment by teoljungberg** [comment]
As you expressed wanting to help @pjungwir - is this something you can help get over the finish line?

**Comment by pjungwir** [comment]
I'd be happy to work on this! I want to add Ruby 3 to our Travis/Appraisal files too.

**Comment by teoljungberg** [comment]
See https://github.com/teoljungberg/fx/pull/70 for starters @pjungwir, and if there's anything we ought to re-use.

**Comment by pjungwir** [comment]
This should be fixed by https://github.com/teoljungberg/fx/pull/76.

**Comment by teoljungberg** [comment]
Done as of #76 .
