### ISSUE TITLE
`Fx` is incompatible with `hair_trigger` -- I'm willing to write a PR with some guidance

### ISSUE THREAD

**Issue by XertroV** [teoljungberg/fx#73]
### background

I use [`hair_trigger`](https://github.com/jenseng/hair_trigger) in a project to add triggers which are integral to the DB -- it's used enough that I wrote some basic versioning around it, inspired by `scenic` (which seems v similar to the system `fx` uses).

Yesterday, I was looking for a way to add functions via migrations. Using `execute` works for `rails db:migrate` but doesn't work for tests because schema.rb doesn't record the functions. I couldn't find a way to force the `execute` SQL to be included, so went looking for a gem that could do this for me and found `fx` -- *great!*, I thought. However, `fx` defines `create_trigger`, which `hair_trigger` also defines. this has been problematic.

I tried a few things, like `'fx', require: false` in the gemfile and then `require 'fx'` (and some variants like `require 'fx/functions', and `include Fx::Statements::Function` in the migration) but couldn't get anything working. Searching (many times in different ways) for methods to avoid naming conflicts between gems did not yield useful results.

my (eventual, and very quick) solution was to fork this repo and just [comment all the requires and methods regarding triggers](https://github.com/XertroV/fx/commit/ea114a85e4e5b4bd0a5c03f60d0000dfdc657582), which works well, but isn't really a good, long term, principled solution to the problem.

### ideas on how to solve

The main idea on how to solve this that I have atm is for `fx` to provide *either*:

1. a way to import only one of `trigger` or `function` related statements/adapters (this does not look that simple, but mb there is an elegant way to do it), maybe via `'fx', require: 'function'` in a gemfile; or
2. a way to import everything with alternate names, e.g., `fx_create_function` and `fx_create_trigger`, then maybe have `'fx', require: 'compatibility_names'` in the gemfile, or something.

I think method `1` might be mb an easier PR, but there's a decisive reason to go with method `2`, IMO: I want to start using `fx` for triggers instead of `hair_trigger` -- and that probably requires having both gems loaded simultaneously. I don't think it's a good idea to try and remove `hair_trigger` from past migrations (the webapp isn't live, yet, so this is maybe feasible); the more principled approach feels like going for compatibility over partial requires.

### Writing a PR

If I write a PR for this, is this something that would be merged? (after review, etc)

If so, do you (or does anyone else) have any useful insight/input to this problem and other methods of solving it?

Finally, do you have any hints about how I should approach this? like, where would the best places be to add this sort of thing. I guess that I will need to learn a bit more about gemfiles and requires, but it doesn't seem overly complex.

**Comment by teoljungberg** [comment]
Heya @XertroV - 

I feel your pain, it's always finicky to have conflicting names in either objects or functions. As this is the first time (to my knowledge) someone runs into issues migrating from another gem to fx, I'm hesitant adding first class support for a path that would ease the migration. If anything, I would be willing to support overriding a set of constants to generate the names.

Is the problem the migration helpers, or the additions to the schema dumper (effectively the `create_trigger` and friends in your schema.rb)?

I'd add a compatibility layer into your application to support your migration, and I would suggest migrating fully from hair_trigger to fx.

The steps would off the cuff be something like this.

- Have `gem 'fx', require: false` in your Gemfile.
- Add `fx_compatibility.rb` as an initializer or similar that overrides the conflicting helpers, something like:

```ruby
require 'fx'

module FxCompatibility
  module Statements
    alias_method :create_trigger, :fx_create_trigger
    alias_method :drop_trigger, :fx_drop_trigger
    alias_method :update_trigger, :fx_update_trigger

    def fx_create_trigger(*args, **kwargs)
      create_trigger(*args, **kwargs)
    end

    def fx_drop_trigger(*args, **kwargs)
      drop_trigger(*args, **kwargs)
    end

    def fx_update_trigger(*args, **kwargs)
      drop_trigger(*args, **kwargs)
    end
  end

  module Trigger
    def to_schema
      <<-SCHEMA.indent(2)
create_function :#{name}, sql_definition: <<-'SQL'
#{definition.indent(4).rstrip}
SQL
      SCHEMA
    end
  end

  module SchemaDumper
    alias_method :create_trigger, :fx_create_trigger
    alias_method :drop_trigger, :fx_drop_trigger
    alias_method :update_trigger, :fx_update_trigger

    def create_trigger(*args)
      record(:fx_create_trigger, args)
    end

    def drop_trigger(*args)
      record(:fx_drop_trigger, args)
    end

    def update_trigger(*args)
      record(:fx_update_trigger, args)
    end

    def invert_create_trigger(args)
      [:fx_drop_trigger, args]
    end

    def invert_drop_trigger(args)
      perform_inversion(:fx_create_trigger, args)
    end

    def invert_update_trigger(args)
      perform_inversion(:fx_update_trigger, args)
    end
  end
end

# This adds the new fx_* names to the migrations.
Fx::Statements.include(FxCompatibility::Statements)
# This adds the new fx_* names to what is dumped in the schema, as well making
# them used for rollbacks etc.
Fx::Trigger.include(FxCompatibility::Trigger)
Fx::SchemaDumper.include(FxCompatibility::SchemaDumper)
```

(This is pseudo-coded and I haven't run the above. But something like that should get your started.

**Comment by XertroV** [comment]
Thanks for getting back to me. I'm looking forward to trying a compatibility layer.

> If anything, I would be willing to support overriding a set of constants to generate the names.

I could definitely work with that (if it's necessary)

> Is the problem the migration helpers, or the additions to the schema dumper (effectively the `create_trigger` and friends in your schema.rb)?

Both, I think (I'm fairly new to ruby/rails). The migration helpers are where I mostly ran into problems because that was where I was trying different `include` things. I did get past that bit sometimes tho. The second roadblock I ran into was with testing. I could get create_function to work from the migration file (i.e., run the queries), but the changes wouldn't be reflected in schema.rb (and the initializer config to dump functions first didn't work) -- the particular issue here was that one of my views (via scenic) uses the function, so it needs to be defined before the view is. This manifested as parallel tests breaking -- I think b/c, although the first db can be initialized via db:migrate, the other test dbs are initialized from schema.rb. So the issue was getting access to the migration helpers whilst also getting schema.rb to generate correctly and dump the functions upfront, and then having tests work, still.

Writing the above paragraph, I wonder if this is mb more complex than I first realized.

> I'd add a compatibility layer into your application to support your migration, and I would suggest migrating fully from hair_trigger to fx.

I'm open to this; ideally it shouldn't break existing DBs, but I guess that with some deployment juggling that can be arranged (and the end result is still deployable from scratch). We don't need to be capable of rolling back any DBs to earlier than the hair_trigger -> fx migration, which I guess is a helpful thing in this case.

I think I have some ideas on how to get started, I will report back with updates. Thanks again.

**Comment by teoljungberg** [comment]
Thanks @XertroV - I'll close this issue for now, but please do write back with your findings and if we need to do any additional thinking.

**Comment by XertroV** [comment]
actually, even easier is to fork hair_trigger, rename the relevant things (in xertrov/hair_trigger and my project), and point to that in my gemfile. I don't care about updates to hair_trigger if I'm migrating away from it. Then I can just opportunistically remove triggers from hair_trigger through the normal dev-migration cycle.

> I'll close this issue for now, but please do write back with your findings and if we need to do any additional thinking.

Will do. I'm guessing that if any of this simpler strategies work, then I'll make a PR to the README with some basic instructions and a link to this issue-thread.

Cheers!

**Comment by XertroV** [comment]
I managed to get some decent preliminary results with the renaming (commits: [1](https://github.com/XertroV/hair_trigger/commit/43de1945feda1381658e3d0f597d5498120d0858) [2](https://github.com/XertroV/hair_trigger/commit/ec2bace78778071e62f4396e8353cba8c6db9150) [3](https://github.com/XertroV/hair_trigger/commit/3bc5c8592927f61a65c65df2c519e17ffb48ae7b)), but ended up running into more name conflicts (I think, like `.triggers()`). I noticed (before and after this) that my schema.rb had some extra trigger definition lines, and I think this was due to another interaction between hair_trigger and fx that I previously didn't know was happening. although I did get hair_trigger to work (apparently fine) with the renamed methods, after renaming `.triggers` didn't work I decided to go with a different approach.

## what worked

1. I created a new migration that would execute `DROP IF EXISTS` for the prior functions and triggers. (see below)
2. I commented all the past hair_trigger references, and removed it from my Gemfile.
3. I moved `fx` from my hacky self-hosted version back to mainline.

and that worked fine. I only had 2 actual triggers (each did more than 1 thing, but only 2 triggers in total), so I probably should have realized earlier that a more manual (and less 'clever') method would be easy enough (and I could have mentioned that originally, too). I like good methods, and altering past migrations doesn't feel like that good a method (generally) and might be problematic for some ppl, but works well enough for me in this case.

## feedback on the migration

Fx's readme is adequate atm, but I think it could be improved, and I also think some boilerplate SQL templates would help.

1. re readme: good examples -- there were some things that weren't clear to me that meant I ran into postgres errors that I could have avoided (the errors weren't that bad, just a little time consuming to resolve). I think some more explicit examples of sample files from `db/functions` and `db/triggers` would help.

2. generators -- both trigger and function generators just make an empty SQL file atm but some boilerplate code would go a long way (see below). This would have helped me move faster b/c it becomes much more obvious where to put what SQL. hair_trigger provides more support in this way b/c you only really need to worry about the body of the function; the declaration of the function and return statement are handled by hair_trigger.

Those two things both overlap, but either would have helped. Fx isn't broken without them, but IMO it makes life a little easier for a new user. I ended up reading the tests to figure out exactly what I needed to put where.

## migration

I commented *all* the hairtrigger stuff from past migrations, then used this to recreate them with the same names and on the same tables:

```ruby
class DropHairTriggers < ActiveRecord::Migration[6.1]
  def change
    reversible do |dir|
      dir.up do
        [['nodes_after_insert_row_tr', :nodes],
          ['content_versions_after_insert_row_tr', :content_versions]].each do |(trigger, table)|
          execute <<-SQL
            DROP TRIGGER IF EXISTS #{trigger} ON #{table};
            DROP FUNCTION IF EXISTS #{trigger};
          SQL
        end
        create_function 'nodes_after_insert_row_tr', version: 2
        create_function 'content_versions_after_insert_row_tr'
        create_trigger 'nodes_after_insert_row_tr', on: :nodes, version: 2
        create_trigger 'content_versions_after_insert_row_tr', on: :content_versions, version: 1
      end
      dir.down do
        drop_trigger 'nodes_after_insert_row_tr', on: :nodes
        drop_trigger 'content_versions_after_insert_row_tr', on: :content_versions
        drop_function 'nodes_after_insert_row_tr'
        drop_function 'content_versions_after_insert_row_tr'
      end
    end
  end
end
```

## feedback appendix

### trigger template idea

```sql
-- Define your trigger here. Below is a default for an AFTER trigger calling `my_trigger_func_name` for the `some_table` table.
-- For docs, see: https://www.postgresql.org/docs/13/sql-createtrigger.html

CREATE TRIGGER my_trigger_func_name
    AFTER INSERT ON some_table
    FOR EACH ROW
    EXECUTE PROCEDURE my_trigger_func_name()
```

### function template idea

```sql
-- this defines a function `my_trigger_func_name` that is usable as a trigger.
-- docs: https://www.postgresql.org/docs/13/sql-createfunction.html

CREATE OR REPLACE FUNCTION my_trigger_func_name()
    RETURNS trigger
    LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE some_table st
    SET st.children = ARRAY[NEW.id] || COALESCE(st.children, '{}')
    WHERE st.id = NEW.parent_id;
    -- what you should return depends on the type of trigger function. thus returns NULL because it is an AFTER trigger
    RETURN NULL;
END;
$function$
```

**Comment by teoljungberg** [comment]
Glad the issue sorted itself out. And thanks for the feedback. As the readme already has a few examples, examples I copy paste from time and time when I create new triggers, I think we're in a good spot. I agree that it would be a quality of life improvement to include a boilerplate in the generated sql.
