### ISSUE TITLE
Incorrect cleanup on destroy

### ISSUE THREAD

**Issue by zeeq911** [teoljungberg/fx#77]
Currently if you run the generator with the following for example
```
rails generate fx:function test
```
The generator will create a migration file and an sql function file with paths like the following
```
db/functions/test_v01.sql
db/migrate/20211011202933_create_function_test.rb
```
But when you try to destroy the generated files with the following commad
```
rails destroy fx:function test
```
The generator tries to remove files with paths that don't exist like the following
```
db/functions/test_v02.sql
db/migrate/20211011203016_update_function_test_to_version_2.rb
```
GEM VERSION 0.6.2

**Comment by teoljungberg** [comment]
That PR was never opened, so I'm closing this issue. I'd entertain one if one is opened.
