### ISSUE TITLE
Annotate trigger in model.

### ISSUE THREAD

**Issue by bekicot** [teoljungberg/fx#79]
I don't know if it best in here or in

https://github.com/ctran/annotate_models/

Basically it will be nice if we can see triggers in model. So that we are aware of their existence.

**Comment by teoljungberg** [comment]
I'm not a fan of having these annotations, and it is probably not something I will support. It makes more sense to do in a separate gem, or to have the `annotate_models` gem be aware of functions from f(x) if the application has it installed.
