### ISSUE TITLE
Add wiki explaining how to use the gem

### ISSUE THREAD

**Issue by harry-graham** [teoljungberg/fx#84]
The gem currently doesn't have a wiki, meaning that users have to figure out how to use the gem from:
* the README;
* blog posts about the gem (if there are any);
* the code.

It would be amazing to have some wiki pages explaining the different things that can be achieved with the gem, and the different options that can be used in each situation.

**Comment by teoljungberg** [comment]
Do we need a wiki? If there are news-worthy articles to being up, please do submit a PR and I'll add it to the README.

I think it's up to the developer to find the best tool for the job, I don't want or need to market this gem for it to be used. I'm OK with that.
