### ISSUE TITLE
Ruby 3 compatible release

### ISSUE THREAD

**Issue by JoeDupuis** [teoljungberg/fx#86]
Hi! 
I see that the gem already support Ruby 3, but the release on rubygems doesn't support it (crash when reverting migrations). A ruby 3 compatible release would be helpful.
Is the gem in a releasable state?

**Comment by teoljungberg** [comment]
Heya! I released 0.7.0 to follow what's on master, and the project should be stable enough to be released. If not, we'll cut 0.7.1 with any bugfixes.

**Comment by JoeDupuis** [comment]
Thank you! :tada:
