### ISSUE TITLE
Place functions in subfolders

### ISSUE THREAD

**Issue by Mbuckley0** [teoljungberg/fx#87]
In the app I work on we have quite a lot of functions and it is becoming very messy and difficult to maintain. It would be great if the gem allowed me to specify a subfolder that a function belongs to so that I can place functions into subfolders to categorise them. Ideally this could be done by adding an option to the `create_function` method to specify the subfolder name.

**Comment by teoljungberg** [comment]
I wanted to follow how Rails handles migrations, and they are not namespaced, nor can they be? Right?
